// get all
GET http://localhost:3000/api/users

###

// get one
GET http://localhost:3000/api/users/66cdb905bd534795af361351

###

// create one
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "name": "Matti",
    "password": "secure_pass",
    "bio": "olen Matti"
}

###

// update user
PUT http://localhost:3000/api/users/66cdb9531da1f0746b87b888 HTTP/1.1
content-type: application/json

{
    "bio": "Olenkin Heikki"
}

###

// delete one
DELETE http://localhost:3000/api/users/66cdb905bd534795af361351

###

//login
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "name": "Matti",
    "password": "secure_pass"
}